---
# yamllint disable rule:line-length
version: 1.0.{build}
branches:
  only:
    - master
    - main
    - dev-appveyor
    - test-appveyor
# https://www.appveyor.com/docs/build-environment/#build-worker-images
image: Ubuntu2004
services:
  - docker
clone_depth: 8
build:
  verbosity: detailed
environment:
  VIRUSTOTAL_APIKEY:
    secure: 9SXnYhOkq6CP97zQ+dUc+NzKpKVIoVACMi0wwtLkaUv9y8BimLo5B7XSWBQ9lYwKbQY8JSJ10JFtyxrKRN6O0PK5U7i6bhg4/B6c40ieHHw=
  SIGN_CODE_GPG_PASS:
    secure: N+xoeCLwFHPsb/KBdgOIvJ0NnbVrBI/PLcPkPBTBmedgDVUBlbEZu7HrJcEHNyuR
  SIGN_CODE_KEY_PASS:
    secure: vvbDZUlaB2WICMOD2zqO3MyPRpy3S06hE3ShA0q+YXWDdj4GX+am+RepjZIlpxtB
  SIGN_PKG_KEY_ID: 002C168965BAC2202118408B4ED85DF9BB3D0DE8
  SIGN_PKG_GPG_PASS:
    secure: YlApXMCfpUnsOjXyLc9mgEnIoaUShFBc5dhHVOo6KpgSEmWpevGLWd0RDORsD9ex
  SIGN_PKG_KEY_PASS:
    secure: 9FJBUF1mskStuU+7o9r6hsQub+XWNiXWtznlEYbFzv2Gl7bneSt44KBrstMLTDUj
  DEPLOY_GPG_PASS:
    secure: WHnaUtu4NM46WEgLhxUyPBShvzLNwRoR5v0Z3+/UqM0nMzrUGieb+tJKX/AZLFkx
  CC: mingw-clang
  DO_NOT_TRACK: 1
build_script:
  - sh: |
      export DOCKER_IMAGE='debian:testing'
      time docker pull "${DOCKER_IMAGE}"
      docker images --digests
      time docker run --volume "$(pwd):$(pwd)" --workdir "$(pwd)" \
        --env-file <(env | grep -a -E \
          '^(CC|DO_NOT_TRACK|VIRUSTOTAL_|SIGN_|DEPLOY_|APPVEYOR_|GITLAB_|CI_)') \
        "${DOCKER_IMAGE}" \
        sh -c ./_ci-linux-debian.sh
artifacts:
  - path: '*-*-mingw*.*'
    name: package
  - path: 'all-mingw*.*'
    name: all
# init:
#   - sh: curl --user-agent curl --fail --silent --location --proto-redir =https 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -
